import numpy as np
import matplotlib.pyplot as plt
n=1000
isim=np.empty(n)
mean_C=np.empty(n)
median_C=np.empty(n)
mean_G=np.empty(n)
median_G=np.empty(n)
sigma=1/(np.sqrt(2*np.log(2)))
print(sigma)
for i in range(1,n): 
    data_C=np.array(i)
    data_C=np.tan((np.random.random_sample(i)-0.5)*np.pi)
    data_G=np.array(i)
    data_G=np.random.normal(0,sigma,i)
    isim[i]=i+1
    mean_C[i]=np.mean(data_C)
    median_C[i]=np.median(data_C)
    mean_G[i]=np.mean(data_G)
    median_G[i]=np.median(data_G)
fig,ax=plt.subplots()
ax.set_xlabel("N")
ax.set_ylabel("prumer")
ax.plot(isim,mean_C)    
ax.plot(isim,mean_G,c="red") 
ax.set_xlim(0,n)   
#ax.set_ylim(-1,1)

fig,ax=plt.subplots()
ax.set_xlabel("N")
ax.set_ylabel("prumer")
ax.plot(isim,mean_C)    
ax.plot(isim,mean_G,c="red") 
ax.set_xlim(0,n)       
ax.set_ylim(-10,10)

fig,ax=plt.subplots()
ax.set_xlabel("N")
ax.set_ylabel("prumer")
ax.plot(isim,mean_C)    
ax.plot(isim,mean_G,c="red") 
ax.set_xlim(0,n)       
ax.set_ylim(-1,1)


fig,ax=plt.subplots()
ax.set_xlabel("N")
ax.set_ylabel("median")
ax.plot(isim,median_C)    
ax.plot(isim,median_G,c="red") 
ax.set_xlim(0,n)       
ax.set_ylim(-10,10)

fig,ax=plt.subplots()
ax.set_xlabel("N")
ax.set_ylabel("median")
ax.plot(isim,median_C)    
ax.plot(isim,median_G,c="red") 
ax.set_xlim(0,n)       
ax.set_ylim(-1,1)