import numpy as np
import scipy.special as spec
import matplotlib.pyplot as plt
import scipy.stats as stat
import matplotlib
plt.rcParams.update({"text.usetex": True})

vyska=np.loadtxt("dotaznik.txt",usecols=0)
vaha=np.loadtxt("dotaznik.txt",usecols=1)
mesic=np.loadtxt("dotaznik.txt",usecols=2)
z_vyska=(vyska-np.mean(vyska))/np.std(vyska)
z_vaha=(vaha-np.mean(vaha))/np.std(vaha)
z_mesic=(mesic-np.mean(mesic))/np.std(mesic)
primka=stat.linregress(z_vyska,z_vaha)
z_lr=primka[0]*z_vyska+primka[1]
fig,ax=plt.subplots()
ax.set_title("výška-váha")
ax.set_xlabel("z-výška")
ax.set_ylabel("z-váha")
ax.scatter(z_vyska,z_vaha)
ax.plot(z_vyska,z_lr,c="red")
plt.show()
korelace=np.corrcoef(vyska,vaha)[0,1]*(np.size(vyska)-1)/np.size(vyska)
print("korelace výška, váha:",korelace)
print("Fisherův test:")
F=0.5*np.log((1+korelace)/(1-korelace))
print("F = ",F)
z=F*np.sqrt(np.size(vyska)-3)
print("z = ",z)
print("P = ",2*(1-0.5*(1+spec.erf(np.abs(z)/np.sqrt(2)))))
print("Studentův test:")
t=korelace*np.sqrt((np.size(vyska)-2)/(1-korelace**2))
print("t =",t)
print("P=",2*(1-stat.t.cdf(t,np.size(vyska)-2)))
print("Beta rozdělení:")
pearson,P=stat.pearsonr(vyska,vaha)
print("Pearson koef =",pearson)
print("P=",P)

x=np.linspace(-1,1,100)
y=stat.beta.pdf(x,np.size(vyska/2-1),np.size(vyska/2-1),loc=-1,scale=2)
fig,ax=plt.subplots()
ax.set_xlabel("$\\varrho $")
ax.set_ylabel("$f(\\varrho)$")
ax.plot(x,y)
ax.plot([pearson,pearson],[0,3],c="red")
ax.plot([-pearson,-pearson],[0,3],c="red")
plt.show()
print("............................................................")


primka=stat.linregress(z_vaha,z_mesic)
z_lr=primka[0]*z_vaha+primka[1]
fig,ax=plt.subplots()
ax.set_title("váha-měsíc")
ax.set_xlabel("z-váha")
ax.set_ylabel("z-měsíc")
ax.scatter(z_vaha,z_mesic)
ax.plot(z_vaha,z_lr,c="red")
plt.show()
korelace =np.corrcoef(vaha,mesic)[0,1]*(np.size(vaha)-1)/np.size(vaha)
print("korelace váha, měsíc:",korelace)
print("Fisherův test:")
F=0.5*np.log((1+korelace)/(1-korelace))
print("F = ",F)
z=F*np.sqrt(np.size(vyska)-3)
print("z = ",z)
print("P = ",2*(1-0.5*(1+spec.erf(np.abs(z)/np.sqrt(2)))))
print("Studentův test:")
t=korelace*np.sqrt((np.size(vaha)-2)/(1-korelace**2))
print("t =",t)
print("P=",2*(1-stat.t.cdf(np.abs(t),np.size(vaha)-2)))
print("Beta rozdělení:")
pearson,P=stat.pearsonr(vaha,mesic)
print("Pearson koef =",pearson)
print("P=",P)
x=np.linspace(-1,1,100)
y=stat.beta.pdf(x,np.size(vyska/2-1),np.size(vyska/2-1),loc=-1,scale=2)
fig,ax=plt.subplots()
ax.set_xlabel("$\\varrho $")
ax.set_ylabel("$f(\\varrho)$")
ax.plot(x,y)
ax.plot([pearson,pearson],[0,3],c="red")
ax.plot([-pearson,-pearson],[0,3],c="red")
plt.show()
print("............................................................")

primka=stat.linregress(z_vyska,z_mesic)
z_lr=primka[0]*z_vyska+primka[1]
fig,ax=plt.subplots()
ax.set_title("výška-měsíc")
ax.set_xlabel("z-výška")
ax.set_ylabel("z-měsíc")
ax.scatter(z_vyska,z_mesic)
ax.plot(z_vyska,z_lr,c="red")
plt.show()
korelace =np.corrcoef(vyska,mesic)[0,1]*(np.size(vyska)-1)/np.size(vyska)
print("korelace výška, měsíc:",korelace)
print("Fisherův test:")
F=0.5*np.log((1+korelace)/(1-korelace))
print("F = ",F)
z=F*np.sqrt(np.size(vyska)-3)
print("z = ",z)
print("P = ",2*(1-0.5*(1+spec.erf(np.abs(z)/np.sqrt(2)))))
print("Studentův test:")
t=korelace*np.sqrt((np.size(vyska)-2)/(1-korelace**2))
print("t =",t)
print("P=",2*(1-stat.t.cdf(np.abs(t),np.size(vyska)-2)))
print("Beta rozdělení:")
pearson,P=stat.pearsonr(vyska,mesic)
print("Pearson koef =",pearson)
print("P=",P)
x=np.linspace(-1,1,100)
y=stat.beta.pdf(x,np.size(vyska/2-1),np.size(vyska/2-1),loc=-1,scale=2)
fig,ax=plt.subplots()
ax.set_xlabel("$\\varrho $")
ax.set_ylabel("$f(\\varrho)$")
ax.plot(x,y)
ax.plot([pearson,pearson],[0,3],c="red")
ax.plot([-pearson,-pearson],[0,3],c="red")
plt.show()
print("............................................................")
